Hybrid updates
rwth-i6/i6_experiments pull request #113
Opened 2023-01-09 13:55 UTC by JackTemaki

- support for stm and glm in via data
 - NnSystem manages native op compilation
 - small refactoring
 
 Note: Any recognition args now need to have `"native_ops": ["NativeLstm2"]` to get the old behavior.

2023-01-09 15:44 UTC, vieting commented on common/setups/rasr/nn_system.py
> +        native_lstm_job = returnn.CompileNativeOpJob(
```suggestion
        native_op_job = returnn.CompileNativeOpJob(
```
Same applies a few lines down.

2023-01-09 15:54 UTC, vieting requested changes
Just some small comments.

2023-01-09 15:54 UTC, vieting commented on common/setups/rasr/rasr_system.py
> +                scorer_args if self.rasr_init_args.scorer_args is not None else {}
```suggestion
                scorer_args if scorer_args is not None else {}
```
Would be more consistent with the change above.

2023-01-09 15:54 UTC, vieting commented on common/setups/rasr/nn_system.py
> +        native_lstm_job = returnn.CompileNativeOpJob(
```suggestion
        native_op_job = returnn.CompileNativeOpJob(
```
Same applies a few lines down.

2023-01-09 15:54 UTC, vieting commented on common/setups/rasr/gmm_system.py
> -            tk.register_output(f"lms/{eval_c}.ppl", ppl_job.perplexity)
Is it intended to remove this? It does not seem to be moved somewhere else.

2023-01-10 10:13 UTC, JackTemaki commented on common/setups/rasr/hybrid_system.py
> +        self.train_input_data = None  # type:Optional[Dict[str, ReturnnRasrDataInput]]
Yes, and I thought about adding that, but I did not want to mix it in here yet. So far we anyway have no other input that works properly. We can extend this here once we have that.

2023-01-10 10:39 UTC, christophmluscher approved these changes

2023-01-10 11:13 UTC, vieting approved these changes

2023-01-10 11:14 UTC, merged