TedLium-V2 Dataset
rwth-i6/i6_experiments pull request #127
Opened 2023-04-13 15:05 UTC by christophmluscher

PR for only the data of TedLium-V2.
Split from #111

2023-04-13 15:25 UTC, michelwi commented on common/datasets/tedlium2/lexicon.py
> +    output_prefix="datasets",
```suggestion
    output_prefix: str = "datasets",
```

2023-04-13 15:26 UTC, michelwi commented on common/datasets/tedlium2/lexicon.py
> +    output_prefix="datasets",
```suggestion
    output_prefix: str = "datasets",
```

2023-04-14 06:20 UTC, Atticus1806 reviewed
PR looks good to me, one thing to discuss, otherwise will be approved.

2023-04-14 10:01 UTC, JackTemaki requested changes
Docstrings for every function would be nice, but the important thing is the dataclass->dict conversion which should be removed.

2023-04-14 15:23 UTC, christophmluscher commented on common/datasets/tedlium2/download.py
> +@dataclass()
using the class directly now

2023-04-15 09:29 UTC, DanEnergetics approved these changes
All looks good to me.

2023-04-18 07:13 UTC, Atticus1806 commented
So @JackTemaki all changes adressed? From my side PR is approved, but since you asked for changes I will let you make the last call.

2023-04-18 09:19 UTC, JackTemaki approved these changes
I have to trust you on the lexicon/cart, but in formality all seems fine now.

2023-04-18 09:20 UTC, JackTemaki commented
@christophmluscher @Atticus1806 do you create the folder under `/work/common` or do you want to first see how the pipeline is running until we push the dataset "officially"?

2023-04-18 09:21 UTC, Atticus1806 commented
For now I would run it locally because I think it is not fully functional yet. Datasets should be fine, but recognition results do not seem correct yet.

2023-04-18 09:22 UTC, JackTemaki commented
Okay then lets wait and check if we need a revision also of the data.

2023-04-20 09:13 UTC, christophmluscher commented
@Atticus1806 can we merge this for now? the pipeline is running and we can still do further PRs to change things

2023-04-20 09:17 UTC, Atticus1806 commented
From my end yes.

2023-04-24 08:20 UTC, merged