add new fairseq_pretraining job with starting from cp
rwth-i6/i6_experiments pull request #255
Opened 2024-10-22 08:55 UTC by AndreasPlt

For doing scheduled hard_negatives training, I added `run_fairseq_pretraining_from_checkpoint` job that takes an additional `checkpoint` parameter and runs the pretraining from that checkpoint

2024-10-29 09:24 UTC, AndreasPlt commented
I noticed that this, when using the `checkpoint` parameter, it is not possible to resume training from the last checkpoint when interrupted. 

The reason for that is that, when `checkpoint` is given, fairseq always starts training from that checkpoint and not from `checkpoint_last`. On the other hand, when removing the `checkpoint` parameter in order to make fairseq train from the last checkpoint, the hash changes and `checkpoint_last` is in fact to available anymore. Any ideas, how to solve that elegantly?

2024-12-18 15:28 UTC, vieting requested changes
The function `run_fairseq_pretraining_from_checkpoint` that you introduce has huge overlap with the existing `run_fairseq_pretraining`. Instead of copying the whole function and only changing a small part of it, please add `checkpoint: Optional[tk.Path] = None` as an argument to the existing function and do the modifications you need if it is given, e.g.

```
if checkpoint is not None:
    fairseq_args["checkpoint"]["continue_once"] = checkpoint
```

2024-12-18 16:14 UTC, AndreasPlt commented
Done. Instead of `tk.Path` however, I added `str` as a typehint since I am unsure if fairseq accepts a `tk.Path`. Feel free to correct me if I'm wrong

2025-01-07 12:27 UTC, vieting approved these changes

2025-01-07 12:27 UTC, merged