extend init to accept rasr binaries
rwth-i6/i6_experiments pull request #67
Opened 2022-06-22 14:41 UTC by christophmluscher

the idea is to set the rasr binaries at the beginning. at the moment this still uses `gs.RASR_*` but we could remove this. it would be cleaner but backward comp?!

2022-06-22 14:41 UTC, christophmluscher commented
we might want to wait for merging until Nicks PR (in preparation) is merged first..

2022-06-22 14:53 UTC, christophmluscher commented on common/setups/rasr/rasr_system.py
> +            self.rasr_root = gs.RASR_ROOT
I would remove `gs.RASR_*` completely

2022-06-22 15:00 UTC, michelwi commented
> it would be cleaner but backward comp?!

yes, I also agree to remove it completely. If a user wants to use a specific RASR version from a certain path in the FS, then he could just give it as a Path object to this function.

But now the argument `rasr_root` should be required and not optional. and `rasr_arch` can default to "linux-x86_64-standard" and then you can remove the if-else-logic when you set it later.

2022-06-23 15:07 UTC, JackTemaki commented on common/setups/rasr/gmm_system.py
> +        rasr_root: Optional[tk.Path] = None,
```suggestion
        rasr_binary_path: Optional[tk.Path] = None,
```
We are not not passing the root, but a path to a folder directly containing the binaries, as they can be independent from the repository.

2022-06-23 15:08 UTC, JackTemaki commented on common/setups/rasr/gmm_system.py
> +        super().__init__(rasr_root=rasr_root, rasr_arch=rasr_arch)
```suggestion
        super().__init__(rasr_binary_path=rasr_binary_path, rasr_arch=rasr_arch)
```

2022-06-23 15:10 UTC, JackTemaki requested changes

2022-06-23 15:10 UTC, JackTemaki commented on common/setups/rasr/rasr_system.py
> +        rasr_root: Optional[tk.Path] = None,
```suggestion
        rasr_binary_path: Optional[tk.Path] = None,
```

2022-06-23 15:10 UTC, JackTemaki commented on common/setups/rasr/rasr_system.py
> +        self.rasr_root = rasr_root
```suggestion
        self.rasr_binary_path = rasr_binary_path
```

2022-06-23 15:10 UTC, JackTemaki commented on common/setups/rasr/rasr_system.py
> +        if self.rasr_root is not None and self.rasr_arch is not None:
```suggestion
        if self.rasr_binary_path is not None and self.rasr_arch is not None:
```

2022-06-23 15:10 UTC, JackTemaki commented on common/setups/rasr/rasr_system.py
> +                rasr_root=self.rasr_root, rasr_arch=self.rasr_arch
```suggestion
                rasr_root=self.rasr_binary_path, rasr_arch=self.rasr_arch
```

2022-06-23 15:10 UTC, JackTemaki commented on common/setups/rasr/rasr_system.py
> +        elif self.rasr_root is not None and self.rasr_arch is None:
```suggestion
        elif self.rasr_binary_path is not None and self.rasr_arch is None:
```

2022-06-23 15:10 UTC, JackTemaki commented on common/setups/rasr/rasr_system.py
> +            self.crp[corpus_key].set_executables(rasr_root=self.rasr_root)
```suggestion
            self.crp[corpus_key].set_executables(rasr_binary_path=self.rasr_binary_path)
```

2022-06-23 17:15 UTC, JackTemaki commented on common/setups/rasr/rasr_system.py
> +                rasr_root=self.rasr_binary_path, rasr_arch=self.rasr_arch
```suggestion
                rasr_binary_path=self.rasr_binary_path, rasr_arch=self.rasr_arch
```

2022-06-23 17:18 UTC, JackTemaki approved these changes

2022-06-24 08:49 UTC, michelwi commented
I still stand to my previous comment/suggestion:

> the argument rasr_root should be required and not optional. and rasr_arch can default to "linux-x86_64-standard" and then you can remove the if-else-logic when you set it later.

And I think a doc string would be helpful to avoid the confusion that chris/me originally had

> We are not not passing the root, but a path to a folder directly containing the binaries, as they can be independent from the repository.

But otherwise I am ok with the current state of the code.

2022-06-27 12:26 UTC, michelwi commented on common/setups/rasr/rasr_system.py
> +
```suggestion
        self.crp[corpus_key].set_executables(
            rasr_binary_path=self.rasr_binary_path, rasr_arch=self.rasr_arch
        )
```
If the defaults are not None any more, we don't need to test for it.

2022-06-27 12:34 UTC, michelwi approved these changes

2022-06-27 12:35 UTC, merged